export const CYBERBAY_LEADERBOARD_URL = process.env.NEXT_PUBLIC_CYBERBAY_URL;
export const STRAPI_URL = process.env.NEXT_PUBLIC_STRAPI_GRAPHQL_URL;
export const STRAPI_ASSETS = process.env.NEXT_PUBLIC_STRAPI_ASSETS;
export const APOLLO_URL = process.env.NEXT_PUBLIC_APOLLO_URL;
export const APOLLO_API_KEY = process.env.NEXT_PUBLIC_APOLLO_API_KEY;
export const RECAPTCHA_SITE_KEY = process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY;
