export const corporateIndistries = [
    "Aerospace",
    "Agriculture & Food Production",
    "Automotive",
    "Business Services",
    "Chemical",
    "Commercial Facilities",
    "Community Services",
    "Consumer Services",
    "Critical Manufacturing",
    "Defense Industrial Base",
    "Education",
    "Emergency Services",
    "Energy & Utilities",
    "Engineering",
    "Financial Services",
    "Food & Beverages",
    "Government & Public Sector",
    "Healthcare & Public Health",
    "Holding Companies & Conglomerates",
    "Hospitality & Tourism",
    "Hospitals & Clinics",
    "IT Manufacturing",
    "Information Technology (IT)",
    "Insurance",
    "Internet & Telecommunication Services",
    "Legal Services",
    "Marketing & Advertising",
    "Media & Broadcasting",
    "Minerals & Mining",
    "Nuclear Energy",
    "Real Estate",
    "Shipping & Logistics",
    "Social Services & Non-Profits",
    "Software",
    "Telecommunications",
    "Transportation Systems",
    "Utilities & Waste Management",
    "Wholesale & Retail Trade",
    "Others",
] as const;