export const createCountryFlagUrl = (iso2: string, size='1x1') => {
	return `/images/flags/${size}/${iso2.toLocaleLowerCase()}.svg` as const;
}

export const countries = [
	{
		name: "Afghanistan",
		demonym: "Afghan",
		flag: createCountryFlagUrl("AF"),
		iso2: "AF",
		iso3: "AFG",
	},
	{
		name: "Aland Islands",
		demonym: "Alandic",
		flag: createCountryFlagUrl("AX"),
		iso2: "AX",
		iso3: "ALA",
	},
	{
		name: "Albania",
		demonym: "Albanian",
		flag: createCountryFlagUrl("AL"),
		iso2: "AL",
		iso3: "ALB",
	},
	{
		name: "Algeria",
		demonym: "Algerian",
		flag: createCountryFlagUrl("DZ"),
		iso2: "DZ",
		iso3: "DZA",
	},
	{
		name: "American Samoa",
		demonym: "American Samoan",
		flag: createCountryFlagUrl("AS"),
		iso2: "AS",
		iso3: "ASM",
	},
	{
		name: "Andorra",
		demonym: "Andorran",
		flag: createCountryFlagUrl("AD"),
		iso2: "AD",
		iso3: "AND",
	},
	{
		name: "Angola",
		demonym: "Angolan",
		flag: createCountryFlagUrl("AO"),
		iso2: "AO",
		iso3: "AGO",
	},
	{
		name: "Anguilla",
		demonym: "Anguillian",
		flag: createCountryFlagUrl("AI"),
		iso2: "AI",
		iso3: "AIA",
	},
	{
		name: "Antigua and Barbuda",
		demonym: "Antiguan Barbudan",
		flag: createCountryFlagUrl("AG"),
		iso2: "AG",
		iso3: "ATG",
	},
	{
		name: "Argentina",
		demonym: "Argentinian",
		flag: createCountryFlagUrl("AR"),
		iso2: "AR",
		iso3: "ARG",
	},
	{
		name: "Armenia",
		demonym: "Armenian",
		flag: createCountryFlagUrl("AM"),
		iso2: "AM",
		iso3: "ARM",
	},
	{
		name: "Aruba",
		demonym: "Arubian",
		flag: createCountryFlagUrl("AW"),
		iso2: "AW",
		iso3: "ABW",
	},
	{
		name: "Australia",
		demonym: "Australian",
		flag: createCountryFlagUrl("AU"),
		iso2: "AU",
		iso3: "AUS",
	},
	{
		name: "Austria",
		demonym: "Austrian",
		flag: createCountryFlagUrl("AT"),
		iso2: "AT",
		iso3: "AUT",
	},
	{
		name: "Azerbaijan",
		demonym: "Azerbaijani",
		flag: createCountryFlagUrl("AZ"),
		iso2: "AZ",
		iso3: "AZE",
	},
	{
		name: "Bahamas",
		demonym: "Bahamian",
		flag: createCountryFlagUrl("BS"),
		iso2: "BS",
		iso3: "BHS",
	},
	{
		name: "Bahrain",
		demonym: "Bahraini",
		flag: createCountryFlagUrl("BH"),
		iso2: "BH",
		iso3: "BHR",
	},
	{
		name: "Bangladesh",
		demonym: "Bengali",
		flag: createCountryFlagUrl("BD"),
		iso2: "BD",
		iso3: "BGD",
	},
	{
		name: "Barbados",
		demonym: "Barbadian",
		flag: createCountryFlagUrl("BB"),
		iso2: "BB",
		iso3: "BRB",
	},
	{
		name: "Belarus",
		demonym: "Belarusian",
		flag: createCountryFlagUrl("BY"),
		iso2: "BY",
		iso3: "BLR",
	},
	{
		name: "Belgium",
		demonym: "Belgian",
		flag: createCountryFlagUrl("BE"),
		iso2: "BE",
		iso3: "BEL",
	},
	{
		name: "Belize",
		demonym: "Belizean",
		flag: createCountryFlagUrl("BZ"),
		iso2: "BZ",
		iso3: "BLZ",
	},
	{
		name: "Benin",
		demonym: "Beninese",
		flag: createCountryFlagUrl("BJ"),
		iso2: "BJ",
		iso3: "BEN",
	},
	{
		name: "Bermuda",
		demonym: "Bermudian",
		flag: createCountryFlagUrl("BM"),
		iso2: "BM",
		iso3: "BMU",
	},
	{
		name: "Bhutan",
		demonym: "Bhutanese",
		flag: createCountryFlagUrl("BT"),
		iso2: "BT",
		iso3: "BTN",
	},
	{
		name: "Bolivia",
		demonym: "Bolivian",
		flag: createCountryFlagUrl("BO"),
		iso2: "BO",
		iso3: "BOL",
	},
	{
		name: "Bonaire, Sint Eustatius and Saba",
		demonym: "Dutch",
		flag: createCountryFlagUrl("BQ"),
		iso2: "BQ",
		iso3: "BES",
	},
	{
		name: "Bosnia and Herzegovina",
		demonym: "Bosnian",
		flag: createCountryFlagUrl("BA"),
		iso2: "BA",
		iso3: "BIH",
	},
	{
		name: "Botswana",
		demonym: "Batswana",
		flag: createCountryFlagUrl("BW"),
		iso2: "BW",
		iso3: "BWA",
	},
	{
		name: "Brazil",
		demonym: "Brazilian",
		flag: createCountryFlagUrl("BR"),
		iso2: "BR",
		iso3: "BRA",
	},
	{
		name: "British Virgin Islands",
		demonym: "British Virgin Islander",
		flag: createCountryFlagUrl("VG"),
		iso2: "VG",
		iso3: "VGB",
	},
	{
		name: "Brunei",
		demonym: "Bruneian",
		flag: createCountryFlagUrl("BN"),
		iso2: "BN",
		iso3: "BRN",
	},
	{
		name: "Bulgaria",
		demonym: "Bulgarian",
		flag: createCountryFlagUrl("BG"),
		iso2: "BG",
		iso3: "BGR",
	},
	{
		name: "Burkina Faso",
		demonym: "Burkinabé",
		flag: createCountryFlagUrl("BF"),
		iso2: "BF",
		iso3: "BFA",
	},
	{
		name: "Burundi",
		demonym: "Burundian",
		flag: createCountryFlagUrl("BI"),
		iso2: "BI",
		iso3: "BDI",
	},
	{
		name: "Cambodia",
		demonym: "Cambodian",
		flag: createCountryFlagUrl("KH"),
		iso2: "KH",
		iso3: "KHM",
	},
	{
		name: "Cameroon",
		demonym: "Cameroonian",
		flag: createCountryFlagUrl("CM"),
		iso2: "CM",
		iso3: "CMR",
	},
	{
		name: "Canada",
		demonym: "Canadian",
		flag: createCountryFlagUrl("CA"),
		iso2: "CA",
		iso3: "CAN",
	},
	{
		name: "Cape Verde",
		demonym: "Cape Verdean",
		flag: createCountryFlagUrl("CV"),
		iso2: "CV",
		iso3: "CPV",
	},
	{
		name: "Cayman Islands",
		demonym: "Caymanian",
		flag: createCountryFlagUrl("KY"),
		iso2: "KY",
		iso3: "CYM",
	},
	{
		name: "Central African Republic",
		demonym: "Central African",
		flag: createCountryFlagUrl("CF"),
		iso2: "CF",
		iso3: "CAF",
	},
	{
		name: "Chad",
		demonym: "Chadian",
		flag: createCountryFlagUrl("TD"),
		iso2: "TD",
		iso3: "TCD",
	},
	{
		name: "Chile",
		demonym: "Chilean",
		flag: createCountryFlagUrl("CL"),
		iso2: "CL",
		iso3: "CHL",
	},
	{
		name: "China",
		demonym: "Chinese",
		flag: createCountryFlagUrl("CN"),
		iso2: "CN",
		iso3: "CHN",
	},
	{
		name: "Christmas Island",
		demonym: "Christmas Islander",
		flag: createCountryFlagUrl("CX"),
		iso2: "CX",
		iso3: "CXR",
	},
	{
		name: "Cocos Islands",
		demonym: "Cocos Islandian",
		flag: createCountryFlagUrl("CC"),
		iso2: "CC",
		iso3: "CCK",
	},
	{
		name: "Colombia",
		demonym: "Colombian",
		flag: createCountryFlagUrl("CO"),
		iso2: "CO",
		iso3: "COL",
	},
	{
		name: "Comoros",
		demonym: "Comorian",
		flag: createCountryFlagUrl("KM"),
		iso2: "KM",
		iso3: "COM",
	},
	{
		name: "Congo",
		demonym: "Congolese",
		flag: createCountryFlagUrl("CG"),
		iso2: "CG",
		iso3: "COG",
	},
	{
		name: "Cook Islands",
		demonym: "Cook Islander",
		flag: createCountryFlagUrl("CK"),
		iso2: "CK",
		iso3: "COK",
	},
	{
		name: "Costa Rica",
		demonym: "Costa Rican",
		flag: createCountryFlagUrl("CR"),
		iso2: "CR",
		iso3: "CRI",
	},
	{
		name: "Côte d'Ivoire",
		demonym: "Ivorian",
		flag: createCountryFlagUrl("CI"),
		iso2: "CI",
		iso3: "CIV",
	},
	{
		name: "Croatia",
		demonym: "Croatian",
		flag: createCountryFlagUrl("HR"),
		iso2: "HR",
		iso3: "HRV",
	},
	{
		name: "Cuba",
		demonym: "Cuban",
		flag: createCountryFlagUrl("CU"),
		iso2: "CU",
		iso3: "CUB",
	},
	{
		name: "Curaçao",
		demonym: "Curaçaoan",
		flag: createCountryFlagUrl("CW"),
		iso2: "CW",
		iso3: "CUW",
	},
	{
		name: "Cyprus",
		demonym: "Cypriot",
		flag: createCountryFlagUrl("CY"),
		iso2: "CY",
		iso3: "CYP",
	},
	{
		name: "Czech Republic",
		demonym: "Czech",
		flag: createCountryFlagUrl("CZ"),
		iso2: "CZ",
		iso3: "CZE",
	},
	{
		name: "Democratic Republic of the Congo",
		demonym: "Democratic Republic Congolese",
		flag: createCountryFlagUrl("CD"),
		iso2: "CD",
		iso3: "COD",
	},
	{
		name: "Denmark",
		demonym: "Danish",
		flag: createCountryFlagUrl("DK"),
		iso2: "DK",
		iso3: "DNK",
	},
	{
		name: "Djibouti",
		demonym: "Djiboutian",
		flag: createCountryFlagUrl("DJ"),
		iso2: "DJ",
		iso3: "DJI",
	},
	{
		name: "Dominica",
		demonym: "Dominican",
		flag: createCountryFlagUrl("DM"),
		iso2: "DM",
		iso3: "DMA",
	},
	{
		name: "Dominican Republic",
		demonym: "Dominican Quisqueyan",
		flag: createCountryFlagUrl("DO"),
		iso2: "DO",
		iso3: "DOM",
	},
	{
		name: "Ecuador",
		demonym: "Ecuadorian",
		flag: createCountryFlagUrl("EC"),
		iso2: "EC",
		iso3: "ECU",
	},
	{
		name: "Egypt",
		demonym: "Egyptian",
		flag: createCountryFlagUrl("EG"),
		iso2: "EG",
		iso3: "EGY",
	},
	{
		name: "El Salvador",
		demonym: "Salvadoran",
		flag: createCountryFlagUrl("SV"),
		iso2: "SV",
		iso3: "SLV",
	},
	{
		name: "Equatorial Guinea",
		demonym: "Equatoguinean",
		flag: createCountryFlagUrl("GQ"),
		iso2: "GQ",
		iso3: "GNQ",
	},
	{
		name: "Eritrea",
		demonym: "Eritrean",
		flag: createCountryFlagUrl("ER"),
		iso2: "ER",
		iso3: "ERI",
	},
	{
		name: "Estonia",
		demonym: "Estonian",
		flag: createCountryFlagUrl("EE"),
		iso2: "EE",
		iso3: "EST",
	},
	{
		name: "Ethiopia",
		demonym: "Ethiopian",
		flag: createCountryFlagUrl("ET"),
		iso2: "ET",
		iso3: "ETH",
	},
	{
		name: "Falkland Islands",
		demonym: "Falkland Islander",
		flag: createCountryFlagUrl("FK"),
		iso2: "FK",
		iso3: "FLK",
	},
	{
		name: "Faroe Islands",
		demonym: "Faroese",
		flag: createCountryFlagUrl("FO"),
		iso2: "FO",
		iso3: "FRO",
	},
	{
		name: "Fiji",
		demonym: "Fijian",
		flag: createCountryFlagUrl("FJ"),
		iso2: "FJ",
		iso3: "FJI",
	},
	{
		name: "Finland",
		demonym: "Finnish",
		flag: createCountryFlagUrl("FI"),
		iso2: "FI",
		iso3: "FIN",
	},
	{
		name: "France",
		demonym: "French",
		flag: createCountryFlagUrl("FR"),
		iso2: "FR",
		iso3: "FRA",
	},
	{
		name: "French Guiana",
		demonym: "Guianan",
		flag: createCountryFlagUrl("GF"),
		iso2: "GF",
		iso3: "GUF",
	},
	{
		name: "French Polynesia",
		demonym: "French Polynesian",
		flag: createCountryFlagUrl("PF"),
		iso2: "PF",
		iso3: "PYF",
	},
	{
		name: "Gabon",
		demonym: "Gabonese",
		flag: createCountryFlagUrl("GA"),
		iso2: "GA",
		iso3: "GAB",
	},
	{
		name: "Gambia",
		demonym: "Gambian",
		flag: createCountryFlagUrl("GM"),
		iso2: "GM",
		iso3: "GMB",
	},
	{
		name: "Georgia",
		demonym: "Georgian",
		flag: createCountryFlagUrl("GE"),
		iso2: "GE",
		iso3: "GEO",
	},
	{
		name: "Germany",
		demonym: "German",
		flag: createCountryFlagUrl("DE"),
		iso2: "DE",
		iso3: "DEU",
	},
	{
		name: "Ghana",
		demonym: "Ghanaian",
		flag: createCountryFlagUrl("GH"),
		iso2: "GH",
		iso3: "GHA",
	},
	{
		name: "Gibraltar",
		demonym: "Gibraltarian",
		flag: createCountryFlagUrl("GI"),
		iso2: "GI",
		iso3: "GIB",
	},
	{
		name: "Greece",
		demonym: "Greek",
		flag: createCountryFlagUrl("GR"),
		iso2: "GR",
		iso3: "GRC",
	},
	{
		name: "Greenland",
		demonym: "Greenlander",
		flag: createCountryFlagUrl("GL"),
		iso2: "GL",
		iso3: "GRL",
	},
	{
		name: "Grenada",
		demonym: "Grenadian",
		flag: createCountryFlagUrl("GD"),
		iso2: "GD",
		iso3: "GRD",
	},
	{
		name: "Guadeloupe",
		demonym: "Guadeloupean",
		flag: createCountryFlagUrl("GP"),
		iso2: "GP",
		iso3: "GLP",
	},
	{
		name: "Guam",
		demonym: "Guamanian",
		flag: createCountryFlagUrl("GU"),
		iso2: "GU",
		iso3: "GUM",
	},
	{
		name: "Guatemala",
		demonym: "Guatemalan",
		flag: createCountryFlagUrl("GT"),
		iso2: "GT",
		iso3: "GTM",
	},
	{
		name: "Guernsey",
		demonym: "Guernseymen",
		flag: createCountryFlagUrl("GG"),
		iso2: "GG",
		iso3: "GGY",
	},
	{
		name: "Guinea-Bissau",
		demonym: "Bissau-Guinean",
		flag: createCountryFlagUrl("GW"),
		iso2: "GW",
		iso3: "GNB",
	},
	{
		name: "Guinea",
		demonym: "Guinean",
		flag: createCountryFlagUrl("GN"),
		iso2: "GN",
		iso3: "GIN",
	},
	{
		name: "Guyana",
		demonym: "Guyanese",
		flag: createCountryFlagUrl("GY"),
		iso2: "GY",
		iso3: "GUY",
	},
	{
		name: "Haiti",
		demonym: "Haitian",
		flag: createCountryFlagUrl("HT"),
		iso2: "HT",
		iso3: "HTI",
	},
	{
		name: "Holy See",
		demonym: "Papal",
		flag: createCountryFlagUrl("VA"),
		iso2: "VA",
		iso3: "VAT",
		altSpellings: ["Vatican"],
	},
	{
		name: "Honduras",
		demonym: "Honduran",
		flag: createCountryFlagUrl("HN"),
		iso2: "HN",
		iso3: "HND",
	},
	{
		name: "Hong Kong",
		demonym: "Hong Kongese",
		flag: createCountryFlagUrl("HK"),
		iso2: "HK",
		iso3: "HKG",
	},
	{
		name: "Hungary",
		demonym: "Hungarian",
		flag: createCountryFlagUrl("HU"),
		iso2: "HU",
		iso3: "HUN",
	},
	{
		name: "Iceland",
		demonym: "Icelander",
		flag: createCountryFlagUrl("IS"),
		iso2: "IS",
		iso3: "ISL",
	},
	{
		name: "India",
		demonym: "Indian",
		flag: createCountryFlagUrl("IN"),
		iso2: "IN",
		iso3: "IND",
	},
	{
		name: "Indonesia",
		demonym: "Indonesian",
		flag: createCountryFlagUrl("ID"),
		iso2: "ID",
		iso3: "IDN",
	},
	{
		name: "British Indian Ocean Territory",
		demonym: "British Indian Oceanian",
		flag: createCountryFlagUrl("IO"),
		iso2: "IO",
		iso3: "IOT",
	},
	{
		name: "Iran",
		demonym: "Iranian",
		flag: createCountryFlagUrl("IR"),
		iso2: "IR",
		iso3: "IRN",
	},
	{
		name: "Iraq",
		demonym: "Iraqi",
		flag: createCountryFlagUrl("IQ"),
		iso2: "IQ",
		iso3: "IRQ",
	},
	{
		name: "Ireland",
		demonym: "Irish",
		flag: createCountryFlagUrl("IE"),
		iso2: "IE",
		iso3: "IRL",
	},
	{
		name: "Isle of Man",
		demonym: "Manx",
		flag: createCountryFlagUrl("IM"),
		iso2: "IM",
		iso3: "IMN",
	},
	{
		name: "Israel",
		demonym: "Israeli",
		flag: createCountryFlagUrl("IL"),
		iso2: "IL",
		iso3: "ISR",
	},
	{
		name: "Italy",
		demonym: "Italian",
		flag: createCountryFlagUrl("IT"),
		iso2: "IT",
		iso3: "ITA",
	},
	{
		name: "Jamaica",
		demonym: "Jamaican",
		flag: createCountryFlagUrl("JM"),
		iso2: "JM",
		iso3: "JAM",
	},
	{
		name: "Japan",
		demonym: "Japanese",
		flag: createCountryFlagUrl("JP"),
		iso2: "JP",
		iso3: "JPN",
	},
	{
		name: "Jersey",
		demonym: "Jerseyman",
		flag: createCountryFlagUrl("JE"),
		iso2: "JE",
		iso3: "JEY",
	},
	{
		name: "Jordan",
		demonym: "Jordanian",
		flag: createCountryFlagUrl("JO"),
		iso2: "JO",
		iso3: "JOR",
	},
	{
		name: "Kazakhstan",
		demonym: "Kazakhstani",
		flag: createCountryFlagUrl("KZ"),
		iso2: "KZ",
		iso3: "KAZ",
	},
	{
		name: "Kenya",
		demonym: "Kenyan",
		flag: createCountryFlagUrl("KE"),
		iso2: "KE",
		iso3: "KEN",
	},
	{
		name: "Kiribati",
		demonym: "I-Kiribati",
		flag: createCountryFlagUrl("KI"),
		iso2: "KI",
		iso3: "KIR",
	},
	{
		name: "Kosovo",
		demonym: "Kosovar",
		flag: createCountryFlagUrl("XK"),
		iso2: "XK",
		iso3: "XXK",
	},
	{
		name: "Kuwait",
		demonym: "Kuwaiti",
		flag: createCountryFlagUrl("KW"),
		iso2: "KW",
		iso3: "KWT",
	},
	{
		name: "Kyrgyzstan",
		demonym: "Kyrgyzstani",
		flag: createCountryFlagUrl("KG"),
		iso2: "KG",
		iso3: "KGZ",
	},
	{
		name: "Laos",
		demonym: "Lao",
		flag: createCountryFlagUrl("LA"),
		iso2: "LA",
		iso3: "LAO",
	},
	{
		name: "Latvia",
		demonym: "Latvian",
		flag: createCountryFlagUrl("LV"),
		iso2: "LV",
		iso3: "LVA",
	},
	{
		name: "Lebanon",
		demonym: "Lebanese",
		flag: createCountryFlagUrl("LB"),
		iso2: "LB",
		iso3: "LBN",
	},
	{
		name: "Lesotho",
		demonym: "Lesothonian",
		flag: createCountryFlagUrl("LS"),
		iso2: "LS",
		iso3: "LSO",
	},
	{
		name: "Liberia",
		demonym: "Liberian",
		flag: createCountryFlagUrl("LR"),
		iso2: "LR",
		iso3: "LBR",
	},
	{
		name: "Libya",
		demonym: "Libyan",
		flag: createCountryFlagUrl("LY"),
		iso2: "LY",
		iso3: "LBY",
	},
	{
		name: "Liechtenstein",
		demonym: "Liechtensteiner",
		flag: createCountryFlagUrl("LI"),
		iso2: "LI",
		iso3: "LIE",
	},
	{
		name: "Lithuania",
		demonym: "Lithuanian",
		flag: createCountryFlagUrl("LT"),
		iso2: "LT",
		iso3: "LTU",
	},
	{
		name: "Luxembourg",
		demonym: "Luxembourgish",
		flag: createCountryFlagUrl("LU"),
		iso2: "LU",
		iso3: "LUX",
	},
	{
		name: "Macao",
		demonym: "Macau",
		flag: createCountryFlagUrl("MO"),
		iso2: "MO",
		iso3: "MAC",
	},
	{
		name: "Madagascar",
		demonym: "Malagasy",
		flag: createCountryFlagUrl("MG"),
		iso2: "MG",
		iso3: "MDG",
	},
	{
		name: "Malawi",
		demonym: "Malawian",
		flag: createCountryFlagUrl("MW"),
		iso2: "MW",
		iso3: "MWI",
	},
	{
		name: "Malaysia",
		demonym: "Malaysian",
		flag: createCountryFlagUrl("MY"),
		iso2: "MY",
		iso3: "MYS",
	},
	{
		name: "Maldives",
		demonym: "Maldivian",
		flag: createCountryFlagUrl("MV"),
		iso2: "MV",
		iso3: "MDV",
	},
	{
		name: "Mali",
		demonym: "Malian",
		flag: createCountryFlagUrl("ML"),
		iso2: "ML",
		iso3: "MLI",
	},
	{
		name: "Malta",
		demonym: "Maltese",
		flag: createCountryFlagUrl("MT"),
		iso2: "MT",
		iso3: "MLT",
	},
	{
		name: "Marshall Islands",
		demonym: "Marshallese",
		flag: createCountryFlagUrl("MH"),
		iso2: "MH",
		iso3: "MHL",
	},
	{
		name: "Martinique",
		demonym: "Martinican",
		flag: createCountryFlagUrl("MQ"),
		iso2: "MQ",
		iso3: "MTQ",
	},
	{
		name: "Mauritania",
		demonym: "Mauritanian",
		flag: createCountryFlagUrl("MR"),
		iso2: "MR",
		iso3: "MRT",
	},
	{
		name: "Mauritius",
		demonym: "Mauritian",
		flag: createCountryFlagUrl("MU"),
		iso2: "MU",
		iso3: "MUS",
	},
	{
		name: "Mayotte",
		demonym: "Mahoran",
		flag: createCountryFlagUrl("YT"),
		iso2: "YT",
		iso3: "MYT",
	},
	{
		name: "Mexico",
		demonym: "Mexican",
		flag: createCountryFlagUrl("MX"),
		iso2: "MX",
		iso3: "MEX",
	},
	{
		name: "Micronesia",
		demonym: "Micronesian",
		flag: createCountryFlagUrl("FM"),
		iso2: "FM",
		iso3: "FSM",
	},
	{
		name: "Moldova",
		demonym: "Moldovan",
		flag: createCountryFlagUrl("MD"),
		iso2: "MD",
		iso3: "MDA",
	},
	{
		name: "Monaco",
		demonym: "Monegasque",
		flag: createCountryFlagUrl("MC"),
		iso2: "MC",
		iso3: "MCO",
	},
	{
		name: "Mongolia",
		demonym: "Mongolian",
		flag: createCountryFlagUrl("MN"),
		iso2: "MN",
		iso3: "MNG",
	},
	{
		name: "Montenegro",
		demonym: "Montenegrin",
		flag: createCountryFlagUrl("ME"),
		iso2: "ME",
		iso3: "MNE",
	},
	{
		name: "Montserrat",
		demonym: "Montserratian",
		flag: createCountryFlagUrl("MS"),
		iso2: "MS",
		iso3: "MSR",
	},
	{
		name: "Morocco",
		demonym: "Moroccan",
		flag: createCountryFlagUrl("MA"),
		iso2: "MA",
		iso3: "MAR",
	},
	{
		name: "Mozambique",
		demonym: "Mozambican",
		flag: createCountryFlagUrl("MZ"),
		iso2: "MZ",
		iso3: "MOZ",
	},
	{
		name: "Myanmar",
		demonym: "Myanma",
		flag: createCountryFlagUrl("MM"),
		iso2: "MM",
		iso3: "MMR",
	},
	{
		name: "Namibia",
		demonym: "Namibian",
		flag: createCountryFlagUrl("NA"),
		iso2: "NA",
		iso3: "NAM",
	},
	{
		name: "Nauru",
		demonym: "Nauruan",
		flag: createCountryFlagUrl("NR"),
		iso2: "NR",
		iso3: "NRU",
	},
	{
		name: "Nepal",
		demonym: "Nepalese",
		flag: createCountryFlagUrl("NP"),
		iso2: "NP",
		iso3: "NPL",
	},
	{
		name: "Netherlands Antilles",
		demonym: "Netherlands Antillean",
		flag: createCountryFlagUrl("AN"),
		iso2: "AN",
		iso3: "ANT",
	},
	{
		name: "Netherlands",
		demonym: "Dutch",
		flag: createCountryFlagUrl("NL"),
		iso2: "NL",
		iso3: "NLD",
	},
	{
		name: "New Caledonia",
		demonym: "New Caledonian",
		flag: createCountryFlagUrl("NC"),
		iso2: "NC",
		iso3: "NCL",
	},
	{
		name: "New Zealand",
		demonym: "New Zealander",
		flag: createCountryFlagUrl("NZ"),
		iso2: "NZ",
		iso3: "NZL",
	},
	{
		name: "Nicaragua",
		demonym: "Nicaraguan",
		flag: createCountryFlagUrl("NI"),
		iso2: "NI",
		iso3: "NIC",
	},
	{
		name: "Niger",
		demonym: "Nigerien",
		flag: createCountryFlagUrl("NE"),
		iso2: "NE",
		iso3: "NER",
	},
	{
		name: "Nigeria",
		demonym: "Nigerian",
		flag: createCountryFlagUrl("NG"),
		iso2: "NG",
		iso3: "NGA",
	},
	{
		name: "Niue",
		demonym: "Niuean",
		flag: createCountryFlagUrl("NU"),
		iso2: "NU",
		iso3: "NIU",
	},
	{
		name: "Norfolk Island",
		demonym: "Norfolk Islander",
		flag: createCountryFlagUrl("NF"),
		iso2: "NF",
		iso3: "NFK",
	},
	{
		name: "North Korea",
		demonym: "North Korea",
		flag: createCountryFlagUrl("KP"),
		iso2: "KP",
		iso3: "PRK",
	},
	{
		name: "North Macedonia",
		demonym: "Macedonian",
		flag: createCountryFlagUrl("MK"),
		iso2: "MK",
		iso3: "MKD",
	},
	{
		name: "Northern Mariana Islands",
		demonym: "Northern Mariana Islander",
		flag: createCountryFlagUrl("MP"),
		iso2: "MP",
		iso3: "MNP",
	},
	{
		name: "Norway",
		demonym: "Norwegian",
		flag: createCountryFlagUrl("NO"),
		iso2: "NO",
		iso3: "NOR",
	},
	{
		name: "Oman",
		demonym: "Omani",
		flag: createCountryFlagUrl("OM"),
		iso2: "OM",
		iso3: "OMN",
	},
	{
		name: "Pakistan",
		demonym: "Pakistani",
		flag: createCountryFlagUrl("PK"),
		iso2: "PK",
		iso3: "PAK",
	},
	{
		name: "Palau",
		demonym: "Palauan",
		flag: createCountryFlagUrl("PW"),
		iso2: "PW",
		iso3: "PLW",
	},
	{
		name: "Palestine",
		demonym: "Palestinian",
		flag: createCountryFlagUrl("PS"),
		iso2: "PS",
		iso3: "PSE",
	},
	{
		name: "Panama",
		demonym: "Panamanian",
		flag: createCountryFlagUrl("PA"),
		iso2: "PA",
		iso3: "PAN",
	},
	{
		name: "Papua New Guinea",
		demonym: "Papua New Guinean",
		flag: createCountryFlagUrl("PG"),
		iso2: "PG",
		iso3: "PNG",
	},
	{
		name: "Paraguay",
		demonym: "Paraguayan",
		flag: createCountryFlagUrl("PY"),
		iso2: "PY",
		iso3: "PRY",
	},
	{
		name: "Peru",
		demonym: "Peruvian",
		flag: createCountryFlagUrl("PE"),
		iso2: "PE",
		iso3: "PER",
	},
	{
		name: "Philippines",
		demonym: "Filipino",
		flag: createCountryFlagUrl("PH"),
		iso2: "PH",
		iso3: "PHL",
	},
	{
		name: "Pitcairn",
		demonym: "Pitcairn Islander",
		flag: createCountryFlagUrl("PN"),
		iso2: "PN",
		iso3: "PCN",
	},
	{
		name: "Poland",
		demonym: "Polish",
		flag: createCountryFlagUrl("PL"),
		iso2: "PL",
		iso3: "POL",
	},
	{
		name: "Portugal",
		demonym: "Portuguese",
		flag: createCountryFlagUrl("PT"),
		iso2: "PT",
		iso3: "PRT",
	},
	{
		name: "Puerto Rico",
		demonym: "Puerto Rican",
		flag: createCountryFlagUrl("PR"),
		iso2: "PR",
		iso3: "PRI",
	},
	{
		name: "Qatar",
		demonym: "Qatari",
		flag: createCountryFlagUrl("QA"),
		iso2: "QA",
		iso3: "QAT",
	},
	{
		name: "Réunion",
		demonym: "Réunionese",
		flag: createCountryFlagUrl("RE"),
		iso2: "RE",
		iso3: "REU",
	},
	{
		name: "Romania",
		demonym: "Romanian",
		flag: createCountryFlagUrl("RO"),
		iso2: "RO",
		iso3: "ROU",
	},
	{
		name: "Russia",
		demonym: "Russian",
		flag: createCountryFlagUrl("RU"),
		iso2: "RU",
		iso3: "RUS",
	},
	{
		name: "Rwanda",
		demonym: "Rwandan",
		flag: createCountryFlagUrl("RW"),
		iso2: "RW",
		iso3: "RWA",
	},
	{
		name: "Saint Barthélemy",
		demonym: "Barthélemois",
		flag: createCountryFlagUrl("BL"),
		iso2: "BL",
		iso3: "BLM",
	},
	{
		name: "Saint Helena, Ascension and Tristan da Cunha",
		demonym: "Ascensionian",
		flag: createCountryFlagUrl("SH"),
		iso2: "SH",
		iso3: "SHN",
		altSpellings: ["Saint Helenian", "Tristanian"],
	},
	{
		name: "Saint Kitts and Nevis",
		demonym: "Kittitian",
		flag: createCountryFlagUrl("KN"),
		iso2: "KN",
		iso3: "KNA",
		altSpellings: ["Nevisian"],
	},
	{
		name: "Saint Lucia",
		demonym: "Saint Lucian",
		flag: createCountryFlagUrl("LC"),
		iso2: "LC",
		iso3: "LCA",
	},
	{
		name: "Saint Martin",
		demonym: "Saint-Martinois",
		flag: createCountryFlagUrl("MF"),
		iso2: "MF",
		iso3: "MAF",
	},
	{
		name: "Saint Pierre and Miquelon",
		demonym: "Saint-Pierrais",
		flag: createCountryFlagUrl("PM"),
		iso2: "PM",
		iso3: "SPM",
	},
	{
		name: "Saint Vincent and the Grenadines",
		demonym: "Saint Vincentian",
		flag: createCountryFlagUrl("VC"),
		iso2: "VC",
		iso3: "VCT",
	},
	{
		name: "Samoa",
		demonym: "Samoan",
		flag: createCountryFlagUrl("WS"),
		iso2: "WS",
		iso3: "WSM",
	},
	{
		name: "San Marino",
		demonym: "Sammarinese",
		flag: createCountryFlagUrl("SM"),
		iso2: "SM",
		iso3: "SMR",
	},
	{
		name: "Sao Tome and Principe",
		demonym: "São Toméan",
		flag: createCountryFlagUrl("ST"),
		iso2: "ST",
		iso3: "STP",
	},
	{
		name: "Saudi Arabia",
		demonym: "Saudi",
		flag: createCountryFlagUrl("SA"),
		iso2: "SA",
		iso3: "SAU",
	},
	{
		name: "Senegal",
		demonym: "Senegalese",
		flag: createCountryFlagUrl("SN"),
		iso2: "SN",
		iso3: "SEN",
	},
	{
		name: "Serbia",
		demonym: "Serbian",
		flag: createCountryFlagUrl("RS"),
		iso2: "RS",
		iso3: "SRB",
	},
	{
		name: "Seychelles",
		demonym: "Seychellois",
		flag: createCountryFlagUrl("SC"),
		iso2: "SC",
		iso3: "SYC",
	},
	{
		name: "Sierra Leone",
		demonym: "Sierra Leonean",
		flag: createCountryFlagUrl("SL"),
		iso2: "SL",
		iso3: "SLE",
	},
	{
		name: "Singapore",
		demonym: "Singaporean",
		flag: createCountryFlagUrl("SG"),
		iso2: "SG",
		iso3: "SGP",
		altSpellings: ["SG", "Singapura", "Republik Singapura"],
	},
	{
		name: "Sint Maarten",
		demonym: "St. Maartener",
		flag: createCountryFlagUrl("SX"),
		iso2: "SX",
		iso3: "SXM",
	},
	{
		name: "Slovakia",
		demonym: "Slovak",
		flag: createCountryFlagUrl("SK"),
		iso2: "SK",
		iso3: "SVK",
	},
	{
		name: "Slovenia",
		demonym: "Slovenian",
		flag: createCountryFlagUrl("SI"),
		iso2: "SI",
		iso3: "SVN",
	},
	{
		name: "Solomon Islands",
		demonym: "Solomon Islander",
		flag: createCountryFlagUrl("SB"),
		iso2: "SB",
		iso3: "SLB",
	},
	{
		name: "Somalia",
		demonym: "Somali",
		flag: createCountryFlagUrl("SO"),
		iso2: "SO",
		iso3: "SOM",
	},
	{
		name: "South Africa",
		demonym: "South African",
		flag: createCountryFlagUrl("ZA"),
		iso2: "ZA",
		iso3: "ZAF",
	},
	{
		name: "South Georgia and the South Sandwich Islands",
		demonym: "South Georgian",
		flag: createCountryFlagUrl("GS"),
		iso2: "GS",
		iso3: "SGS",
	},
	{
		name: "South Korea",
		demonym: "South Korean",
		flag: createCountryFlagUrl("KR"),
		iso2: "KR",
		iso3: "KOR",
		altSpellings: ["Republic of Korea"],
	},
	{
		name: "South Sudan",
		demonym: "South Sudanese",
		flag: createCountryFlagUrl("SS"),
		iso2: "SS",
		iso3: "SSD",
	},
	{
		name: "Spain",
		demonym: "Spanish",
		flag: createCountryFlagUrl("ES"),
		iso2: "ES",
		iso3: "ESP",
	},
	{
		name: "Sri Lanka",
		demonym: "Sri Lankan",
		flag: createCountryFlagUrl("LK"),
		iso2: "LK",
		iso3: "LKA",
	},
	{
		name: "Sudan",
		demonym: "Sudanese",
		flag: createCountryFlagUrl("SD"),
		iso2: "SD",
		iso3: "SDN",
	},
	{
		name: "Suriname",
		demonym: "Surinamese",
		flag: createCountryFlagUrl("SR"),
		iso2: "SR",
		iso3: "SUR",
	},
	{
		name: "Svalbard and Jan Mayen",
		demonym: "Svalbard",
		flag: createCountryFlagUrl("SJ"),
		iso2: "SJ",
		iso3: "SJM",
	},
	{
		name: "Swaziland",
		demonym: "Swazi",
		flag: createCountryFlagUrl("SZ"),
		iso2: "SZ",
		iso3: "SWZ",
	},
	{
		name: "Sweden",
		demonym: "Swedish",
		flag: createCountryFlagUrl("SE"),
		iso2: "SE",
		iso3: "SWE",
	},
	{
		name: "Switzerland",
		demonym: "Swiss",
		flag: createCountryFlagUrl("CH"),
		iso2: "CH",
		iso3: "CHE",
	},
	{
		name: "Syria",
		demonym: "Syrian",
		flag: createCountryFlagUrl("SY"),
		iso2: "SY",
		iso3: "SYR",
	},
	{
		name: "Taiwan",
		demonym: "Taiwanese",
		flag: createCountryFlagUrl("TW"),
		iso2: "TW",
		iso3: "TWN",
	},
	{
		name: "Tajikistan",
		demonym: "Tajik",
		flag: createCountryFlagUrl("TJ"),
		iso2: "TJ",
		iso3: "TJK",
	},
	{
		name: "Tanzania",
		demonym: "Tanzanian",
		flag: createCountryFlagUrl("TZ"),
		iso2: "TZ",
		iso3: "TZA",
	},
	{
		name: "Thailand",
		demonym: "Thai",
		flag: createCountryFlagUrl("TH"),
		iso2: "TH",
		iso3: "THA",
	},
	{
		name: "Timor-Leste",
		demonym: "Timorese",
		flag: createCountryFlagUrl("TL"),
		iso2: "TL",
		iso3: "TLS",
	},
	{
		name: "Togo",
		demonym: "Togolese",
		flag: createCountryFlagUrl("TG"),
		iso2: "TG",
		iso3: "TGO",
	},
	{
		name: "Tokelau",
		demonym: "Tokelauan",
		flag: createCountryFlagUrl("TK"),
		iso2: "TK",
		iso3: "TKL",
	},
	{
		name: "Tonga",
		demonym: "Tongan",
		flag: createCountryFlagUrl("TO"),
		iso2: "TO",
		iso3: "TON",
	},
	{
		name: "Trinidad and Tobago",
		demonym: "Trinidadian and Tobagonian",
		flag: createCountryFlagUrl("TT"),
		iso2: "TT",
		iso3: "TTO",
	},
	{
		name: "Tunisia",
		demonym: "Tunisian",
		flag: createCountryFlagUrl("TN"),
		iso2: "TN",
		iso3: "TUN",
	},
	{
		name: "Turkey",
		demonym: "Turkish",
		flag: createCountryFlagUrl("TR"),
		iso2: "TR",
		iso3: "TUR",
	},
	{
		name: "Turkmenistan",
		demonym: "Turkmenistani",
		flag: createCountryFlagUrl("TM"),
		iso2: "TM",
		iso3: "TKM",
	},
	{
		name: "Turks and Caicos Islands",
		demonym: "Turks and Caicos Islander",
		flag: createCountryFlagUrl("TC"),
		iso2: "TC",
		iso3: "TCA",
	},
	{
		name: "Tuvalu",
		demonym: "Tuvaluan",
		flag: createCountryFlagUrl("TV"),
		iso2: "TV",
		iso3: "TUV",
	},
	{
		name: "Uganda",
		demonym: "Ugandan",
		flag: createCountryFlagUrl("UG"),
		iso2: "UG",
		iso3: "UGA",
	},
	{
		name: "Ukraine",
		demonym: "Ukrainian",
		flag: createCountryFlagUrl("UA"),
		iso2: "UA",
		iso3: "UKR",
	},
	{
		name: "United Arab Emirates",
		demonym: "Emirati",
		flag: createCountryFlagUrl("AE"),
		iso2: "AE",
		iso3: "ARE",
		altSpellings: ["AE", "UAE"],
	},
	{
		name: "United Kingdom",
		demonym: "British",
		flag: createCountryFlagUrl("GB"),
		iso2: "GB",
		iso3: "GBR",
		altSpellings: ["UK"],
	},
	{
		name: "United States Minor Outlying Islands",
		demonym: "American Islander",
		flag: createCountryFlagUrl("UM"),
		iso2: "UM",
		iso3: "UMI",
	},
	{
		name: "United States",
		demonym: "American",
		flag: createCountryFlagUrl("US"),
		iso2: "US",
		iso3: "USA",
		altSpellings: ["USA"],
	},
	{
		name: "Uruguay",
		demonym: "Uruguayan",
		flag: createCountryFlagUrl("UY"),
		iso2: "UY",
		iso3: "URY",
	},
	{
		name: "Uzbekistan",
		demonym: "Uzbek",
		flag: createCountryFlagUrl("UZ"),
		iso2: "UZ",
		iso3: "UZB",
	},
	{
		name: "Vanuatu",
		demonym: "Vanuatuan",
		flag: createCountryFlagUrl("VU"),
		iso2: "VU",
		iso3: "VUT",
	},
	{
		name: "Venezuela",
		demonym: "Venezuelan",
		flag: createCountryFlagUrl("VE"),
		iso2: "VE",
		iso3: "VEN",
	},
	{
		name: "Vietnam",
		demonym: "Vietnamese",
		flag: createCountryFlagUrl("VN"),
		iso2: "VN",
		iso3: "VNM",
		altSpellings: ["Viet Nam", "Republic of Viet Nam", "South Vietnam"],
	},
	{
		name: "Virgin Islands of the United States",
		demonym: "American Virgin Islander",
		flag: createCountryFlagUrl("VI"),
		iso2: "VI",
		iso3: "VIR",
	},
	{
		name: "Wallis and Futuna",
		demonym: "Wallisian",
		flag: createCountryFlagUrl("WF"),
		iso2: "WF",
		iso3: "WLF",
		altSpellings: ["Futunan"],
	},
	{
		name: "Western Sahara",
		demonym: "Western Saharan",
		flag: createCountryFlagUrl("EH"),
		iso2: "EH",
		iso3: "ESH",
	},
	{
		name: "Yemen",
		demonym: "Yemeni",
		flag: createCountryFlagUrl("YE"),
		iso2: "YE",
		iso3: "YEM",
	},
	{
		name: "Zambia",
		demonym: "Zambian",
		flag: createCountryFlagUrl("ZM"),
		iso2: "ZM",
		iso3: "ZMB",
	},
	{
		name: "Zimbabwe",
		demonym: "Zimbabwean",
		flag: createCountryFlagUrl("ZW"),
		iso2: "ZW",
		iso3: "ZWE",
	},
] as const;

export type CountryDataType = (typeof countries)[number];
export type Iso3Code = CountryDataType["iso3"];

export interface CountryData {
	name: string;
	demonym: string;
	flag: string;
	iso2: string;
	iso3: string;
	altSpellings?: string[];
}

export const getAllCountryName = () => {
	return countries.map( (it: CountryDataType) => it.name)
}

export const getAllCountryDemonym = () => {
	return countries.map( (it: CountryDataType) => it.demonym)
}