export * from "./hero";
export * from "./service";
export * from "./organization";
export * from "./faq";
export * from "./partner";
export * from "./objective";
export * from "./demo-form";
export * from "./package"
export * from "./cta"
export * from "./service-list"